-- ============================================================
-- Таблица program_subject (связь программы и предмета)
-- ============================================================
-- Увеличиваем точность до NUMERIC(6,2) – достаточно для любых разумных часов (до 9999.99)
CREATE TABLE IF NOT EXISTS program_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    academic_year INT NOT NULL,
    hours_per_week_for_program NUMERIC(10,2) NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE,
    CONSTRAINT fk_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
    CONSTRAINT uq_program_subject_year UNIQUE (program_id, subject_id, academic_year),
    CHECK (academic_year >= 1)
);

-- Триггер для автоматического обновления updated_at
CREATE TRIGGER trg_update_program_subject_updated_at
    BEFORE UPDATE ON program_subject
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Индексы для ускорения запросов
CREATE INDEX IF NOT EXISTS idx_program_subject_program ON program_subject(program_id);
CREATE INDEX IF NOT EXISTS idx_program_subject_subject ON program_subject(subject_id);
CREATE INDEX IF NOT EXISTS idx_program_subject_year ON program_subject(academic_year);