-- ============================================================
-- Таблица groups (учебные группы)
-- ============================================================
CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    level VARCHAR(100),
    max_students INT,
    status VARCHAR(50) DEFAULT 'active',
    -- Новые поля для учебного процесса
    academic_year INT NOT NULL DEFAULT 1,        -- год обучения (1,2,3...)
    subject_id BIGINT NOT NULL,                 -- предмет, который изучается в группе
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_groups_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE,
    CONSTRAINT fk_groups_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

-- Индекс для быстрого поиска группы по программе, году и предмету
CREATE INDEX idx_groups_program_year_subject ON groups(program_id, academic_year, subject_id);

-- Триггер для обновления updated_at
CREATE TRIGGER trg_update_groups_updated_at
    BEFORE UPDATE ON groups
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();