CREATE TABLE IF NOT EXISTS lesson (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NULL,
    student_id BIGINT NULL,
    subject_id BIGINT NULL,
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    duration_minutes INT NOT NULL,
    room_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    substitute_teacher_id BIGINT NULL,
    lesson_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    notes TEXT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_lesson_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL,
    CONSTRAINT fk_lesson_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_lesson_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
    CONSTRAINT fk_lesson_room FOREIGN KEY (room_id) REFERENCES room(id),
    CONSTRAINT fk_lesson_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
    CONSTRAINT fk_lesson_substitute_teacher FOREIGN KEY (substitute_teacher_id) REFERENCES users(id),
    CONSTRAINT fk_lesson_created_by FOREIGN KEY (created_by) REFERENCES users(id),

    CONSTRAINT lesson_group_or_student_check CHECK (
        (group_id IS NOT NULL AND student_id IS NULL) OR
        (group_id IS NULL AND student_id IS NOT NULL)
    )
);

CREATE TRIGGER trg_update_lesson_updated_at
BEFORE UPDATE ON lesson
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();