-- ============================
-- Таблица новостей (news)
-- ============================
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    author_id BIGINT NOT NULL,
    published_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_news_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_news_author_id ON news(author_id);
CREATE INDEX IF NOT EXISTS idx_news_is_public ON news(is_public);
CREATE INDEX IF NOT EXISTS idx_news_pinned ON news(pinned);
CREATE INDEX IF NOT EXISTS idx_news_created_at ON news(created_at);
CREATE INDEX IF NOT EXISTS idx_news_published_at ON news(published_at);

-- Функция обновления updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Триггер
DROP TRIGGER IF EXISTS trg_news_update ON news;
CREATE TRIGGER trg_news_update
    BEFORE UPDATE ON news
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Комментарии
COMMENT ON TABLE news IS 'Новости и объявления';
COMMENT ON COLUMN news.id IS 'Уникальный идентификатор';
COMMENT ON COLUMN news.title IS 'Заголовок новости';
COMMENT ON COLUMN news.content IS 'Текст новости';
COMMENT ON COLUMN news.author_id IS 'ID автора (ссылка на users)';
COMMENT ON COLUMN news.published_at IS 'Дата и время публикации';
COMMENT ON COLUMN news.is_public IS 'Доступна ли всем пользователям';
COMMENT ON COLUMN news.pinned IS 'Закреплена ли новость наверху';
COMMENT ON COLUMN news.created_at IS 'Дата создания записи';
COMMENT ON COLUMN news.updated_at IS 'Дата последнего обновления';