-- ============================================================
-- 1. Создание ENUM для статуса посещаемости (если не существует)
-- ============================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_status_enum') THEN
        CREATE TYPE attendance_status_enum AS ENUM ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED');
    END IF;
END$$;

-- ============================================================
-- 2. Таблица участников урока (журнал посещаемости и оценок)
-- ============================================================
CREATE TABLE lesson_participant (
    -- Уникальный идентификатор записи (автоинкремент)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Ссылка на урок (связь с таблицей lesson)
    -- При удалении урока все его участники удаляются каскадно
    lesson_id BIGINT NOT NULL,

    -- ID студента (участника урока)
    -- При удалении пользователя записи удаляются каскадно
    user_id BIGINT NOT NULL,

    -- Связь с зачислением студента на программу (опционально)
    -- Используется, если нужно привязать успеваемость к конкретному зачислению
    -- При удалении зачисления поле обнуляется (ON DELETE SET NULL)
    enrollment_id BIGINT NULL,

    -- Статус посещаемости (используется ENUM для строгой типизации)
    attendance_status attendance_status_enum NOT NULL,

    -- Тип оценки (например, 'EXAM', 'TEST', 'SEMESTER', 'CURRENT')
    -- Можно расширить при необходимости, но пока оставляем VARCHAR(20)
    grade_type VARCHAR(20) NOT NULL,

    -- Значение оценки (текстовое, может быть цифра "5", буква "A", или "зачёт")
    grade_value TEXT NULL,

    -- Комментарий преподавателя (например, "Опоздал на 10 мин" или "Не подготовил задание")
    comment TEXT NULL,

    -- Кто произвёл запись (ID пользователя)
    recorded_by BIGINT NOT NULL,

    -- Время первой записи (автоматически проставляется)
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Время последнего изменения (обновляется триггером)
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Внешние ключи
    CONSTRAINT fk_lesson_participant_lesson FOREIGN KEY (lesson_id) REFERENCES lesson(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_participant_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_participant_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_participant_enrollment FOREIGN KEY (enrollment_id) REFERENCES student_program(id) ON DELETE SET NULL,

    -- Уникальность: один студент не может быть дважды добавлен на один урок
    CONSTRAINT uq_lesson_participant_lesson_user UNIQUE (lesson_id, user_id)
);

-- ============================================================
-- 3. Индексы для ускорения запросов
-- ============================================================
CREATE INDEX idx_lesson_participant_lesson_id ON lesson_participant(lesson_id);
CREATE INDEX idx_lesson_participant_user_id ON lesson_participant(user_id);
CREATE INDEX idx_lesson_participant_attendance_status ON lesson_participant(attendance_status);
CREATE INDEX idx_lesson_participant_grade_type ON lesson_participant(grade_type);
CREATE INDEX idx_lesson_participant_recorded_at ON lesson_participant(recorded_at);

-- ============================================================
-- 4. Триггер для автоматического обновления updated_at
-- ============================================================
CREATE TRIGGER trg_update_lesson_participant_updated_at
BEFORE UPDATE ON lesson_participant
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- 5. Комментарии к полям (документация)
-- ============================================================
COMMENT ON TABLE lesson_participant IS 'Журнал посещаемости и оценок – связь урока со студентом, статус посещения, оценка.';
COMMENT ON COLUMN lesson_participant.id IS 'Уникальный идентификатор записи.';
COMMENT ON COLUMN lesson_participant.lesson_id IS 'ID урока (ссылка на lesson).';
COMMENT ON COLUMN lesson_participant.user_id IS 'ID студента (ссылка на users).';
COMMENT ON COLUMN lesson_participant.enrollment_id IS 'ID зачисления студента на программу (опционально, ссылка на student_program).';
COMMENT ON COLUMN lesson_participant.attendance_status IS 'Статус посещаемости: PRESENT (присутствовал), ABSENT (отсутствовал), LATE (опоздал), EXCUSED (по уважительной причине).';
COMMENT ON COLUMN lesson_participant.grade_type IS 'Тип оценки: EXAM, TEST, SEMESTER, CURRENT и т.д.';
COMMENT ON COLUMN lesson_participant.grade_value IS 'Значение оценки: число, буква, "зачёт" и т.п.';
COMMENT ON COLUMN lesson_participant.comment IS 'Комментарий преподавателя к посещаемости или оценке.';
COMMENT ON COLUMN lesson_participant.recorded_by IS 'ID пользователя, который внёс запись (обычно преподаватель).';
COMMENT ON COLUMN lesson_participant.recorded_at IS 'Дата и время создания записи (UTC).';
COMMENT ON COLUMN lesson_participant.updated_at IS 'Дата и время последнего изменения записи (UTC).';
