CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    standard_hours_per_week INT NOT NULL,
    default_program_id BIGINT,
    lesson_type VARCHAR(20) NOT NULL DEFAULT 'GROUP' CHECK (lesson_type IN ('GROUP', 'INDIVIDUAL')),
    min_group_size INT DEFAULT 4,
    max_group_size INT DEFAULT 10,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_default_program FOREIGN KEY (default_program_id) REFERENCES programs(id) ON DELETE SET NULL
);

CREATE TRIGGER trg_update_subjects_updated_at
    BEFORE UPDATE ON subjects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();